global:
  resolve_timeout: 5m
  slack_api_url: <YOUR-SLACK-API-URL>
route:
  group_by: ['namespace', 'job']
  group_interval: 5m
  group_wait: 5m
  receiver: slack
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: 'null'
  - match:
      alertname: AggregatedAPIDown 
    receiver: 'null'
  - match:
      alertname: KubeClientErrors
    receiver: 'null'
  - match:
      alertname: etcdHighNumberOfFailedGRPCRequests
    receiver: 'null'
  - match:
      namespace: cattle-monitoring-system
    receiver: 'null'
  - match:
      namespace: simple-mpesa
    receiver: 'null'
  - match:
      statefulset: activemq-activemq-artemis-slave
    receiver: 'null'
  - match:
      alertname: InfoInhibitor
    receiver: 'null'
  - match:
      severity: info
    receiver: 'null'
  - match:
      severity: warning
    receiver: gmail
    continue: true
  - receiver: slack

  - match:
      severity: critical
    receiver: gmail
    continue: true
  - receiver: slack
receivers:
- name: 'null'
- name: slack
  slack_configs:
  - channel: 'alert-msg'
    send_resolved: true
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
    text: |-
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
      *Description:* {{ .Annotations.description }}
      *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
      *Details:*
      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
      {{ end }}
      {{ end }}
- name: gmail
  email_configs:
      - to: mosip-mec-alert@googlegroups.com
        from: mosip.mec.noreply@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: mosip.mec.noreply@gmail.com
        auth_password: 'password'
